<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="82" started-at="2021-02-22T06:38:52Z" finished-at="2021-02-22T06:38:52Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="82" started-at="2021-02-22T06:38:52Z" finished-at="2021-02-22T06:38:52Z">
      <class name="org.testing.TestScripts.Testcase1">
        <test-method status="SKIP" signature="testcase1(java.lang.String, java.lang.String)[pri:0, instance:org.testing.TestScripts.Testcase1@1df28bb]" name="testcase1" duration-ms="0" started-at="2021-02-22T12:08:52Z" data-provider="dp" finished-at="2021-02-22T12:08:52Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void org.testing.TestScripts.Testcase1.testcase1(java.lang.String,java.lang.String) throws java.io.IOException,java.lang.InterruptedException requires a @DataProvider named : dp]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void org.testing.TestScripts.Testcase1.testcase1(java.lang.String,java.lang.String) throws java.io.IOException,java.lang.InterruptedException requires a @DataProvider named : dp
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:262)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:418)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1276)
	at org.testng.internal.Invoker.createParameters(Invoker.java:992)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1082)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase1 -->
      </class> <!-- org.testing.TestScripts.Testcase1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
